title: Manage Categories
modelClass: PopcornPHP\Market\Models\Category
list: $/popcornphp/market/models/category/columns.yaml
recordUrl: popcornphp/market/categories/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true
showTree: true
#showCheckboxes: true

#defaultSort:
#    column: created_at
#    direction: desc

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_prompt
