relProperty:
    label: properties
    view:
        list: $/popcornphp/market/models/property/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/popcornphp/market/models/property/columns.yaml
        recordsPerPage: 10