title: Manage Products
modelClass: PopcornPHP\Market\Models\Product
list: $/popcornphp/market/models/product/columns.yaml
recordUrl: popcornphp/market/products/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true
#showCheckboxes: true

#defaultSort:
#    column: created_at
#    direction: desc

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_prompt
